// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwGOr5AbJSEh7zJHmar7SpqAgMKHm4eCU',
    appId: '1:240691567508:web:2f252fa4f75336771f0d81',
    messagingSenderId: '240691567508',
    projectId: 'zoomclone-e2fc7',
    authDomain: 'zoomclone-e2fc7.firebaseapp.com',
    storageBucket: 'zoomclone-e2fc7.appspot.com',
    measurementId: 'G-97C3M663CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_JWz4dU-IXfwSfTVlys0s5OAX6IM1Khs',
    appId: '1:240691567508:android:edd38890ea9694521f0d81',
    messagingSenderId: '240691567508',
    projectId: 'zoomclone-e2fc7',
    storageBucket: 'zoomclone-e2fc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvDmOCCtJQBFJ2nT2qKi9iSUitUehz580',
    appId: '1:240691567508:ios:1958ccc2d49242c61f0d81',
    messagingSenderId: '240691567508',
    projectId: 'zoomclone-e2fc7',
    storageBucket: 'zoomclone-e2fc7.appspot.com',
    iosClientId: '240691567508-dpdice1cphobsssh0v3m7acvlrnd3r82.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomCloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvDmOCCtJQBFJ2nT2qKi9iSUitUehz580',
    appId: '1:240691567508:ios:424f9f23e04a96b31f0d81',
    messagingSenderId: '240691567508',
    projectId: 'zoomclone-e2fc7',
    storageBucket: 'zoomclone-e2fc7.appspot.com',
    iosClientId: '240691567508-ulipo9elevhb2g287kvju0acjp10ppkv.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomCloneApp.RunnerTests',
  );
}
